add cache for node and gcloud

diff --git a/.github/workflows/tf-plan.yml b/.github/workflows/tf-plan.yml
--- a/.github/workflows/tf-plan.yml
+++ b/.github/workflows/tf-plan.yml
@@ -40,27 +40,44 @@ jobs:
           if [ -n "${{ secrets.OWNER }}" ]; then echo "TF_VAR_owner=${{ secrets.OWNER }}" >> $GITHUB_ENV; fi
           if [ -n "${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}" ]; then echo "TF_VAR_GCP_WORKLOAD_IDENTITY_PROVIDER_NAME=${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}" >> $GITHUB_ENV; fi
           if [ -n "${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}" ]; then echo "TF_VAR_GCP_WORKLOAD_IDENTITY_SA_EMAIL=${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}" >> $GITHUB_ENV; fi
-      - name: checkout Source
+
+      - name: Checkout Source
         uses: actions/checkout@v4.1.7
+
+      - name: Cache Node.js
+        uses: actions/cache@v4
+        with:
+          path: ~/.npm
+          key: node-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
+          restore-keys: |
+            node-${{ runner.os }}-
 
       - name: Install Node.js
         uses: actions/setup-node@v4.0.3
         with:
           node-version: '20.17.0'
 
-
       - name: Verify Node.js Version
         run: node -v
-      - name: 'Authenticate to Google Cloud'
-        uses: 'google-github-actions/auth@v2.1.5'
+
+      - name: Cache Google Cloud SDK
+        uses: actions/cache@v4
         with:
-          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
-          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
+          path: ~/.config/gcloud
+          key: gcloud-${{ runner.os }}-${{ hashFiles('**/gcloud-config') }}
+          restore-keys: |
+            gcloud-${{ runner.os }}-
 
       - name: Install Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v2.1.1
         with:
           version: 'latest'
+
+      - name: Authenticate to Google Cloud
+        uses: google-github-actions/auth@v2.1.5
+        with:
+          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER_NAME }}
+          service_account: ${{ secrets.GCP_WORKLOAD_IDENTITY_SA_EMAIL }}
 
       - name: Verify Authentication
         run: |
@@ -72,6 +89,7 @@ jobs:
           else
             echo "Authenticated successfully. Organization ID: $ORG_ID"
           fi
+
       - name: Setup Terraform
         uses: hashicorp/setup-terraform@v3.1.2
         with:
@@ -81,6 +99,7 @@ jobs:
         run: |
           echo "TF_PLUGIN_CACHE_DIR=$HOME/.terraform.d/plugin-cache" >>"$GITHUB_ENV"
           mkdir --parents "$HOME/.terraform.d/plugin-cache"
+
       - name: Cache Terraform
         uses: actions/cache@v4
         with:
@@ -140,19 +159,27 @@ jobs:
               body: output
             });
 
-  # tfsec:
-  #   name: tfsec PR commenter
-  #   runs-on: self-hosted
-
+  # checkov:
+  #   runs-on: ubuntu-latest
+  #   needs: [plan]
   #   steps:
-  #     - name: Clone repo
-  #       uses: actions/checkout@master
-  #     - name: tfsec
-  #       uses: aquasecurity/tfsec-pr-commenter-action@v1.2.0
-  #       with:
-  #         tfsec_args: --soft-fail
-  #         github_token: ${{ github.token }}
+  #     - uses: actions/checkout@v4.1.7
 
+  #     - name: Checkov GitHub Action
+  #       uses: bridgecrewio/checkov-action@v12
+  #       with:
+  #         # This will add both a CLI output to the console and create a results.sarif file
+  #         output_format: cli,sarif
+  #         output_file_path: console,results.sarif
+  #         soft_fail: true
+
+  #     - name: Upload SARIF file
+  #       uses: github/codeql-action/upload-sarif@v3.26.6
+  #       if: success() || failure()
+  #       with:
+  #         sarif_file: results.sarif
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
   on-failure:
     runs-on: ubuntu-latest
